"""new begining user v2

Revision ID: 72eee569dabb
Revises: 
Create Date: 2026-01-20 18:47:39.055502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72eee569dabb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resource',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resource_id'), 'learning_resource', ['id'], unique=False)
    op.create_index(op.f('ix_learning_resource_platform'), 'learning_resource', ['platform'], unique=False)
    op.create_index(op.f('ix_learning_resource_resource_type'), 'learning_resource', ['resource_type'], unique=False)
    op.create_index(op.f('ix_learning_resource_title'), 'learning_resource', ['title'], unique=False)
    op.create_table('learning_resource_chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learning_resource_id', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('quiz_generated', sa.Boolean(), nullable=True),
    sa.Column('quiz_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_resource_id', 'title', name='uq_lr_title')
    )
    op.create_index(op.f('ix_learning_resource_chapter_id'), 'learning_resource_chapter', ['id'], unique=False)
    op.create_index(op.f('ix_learning_resource_chapter_index'), 'learning_resource_chapter', ['index'], unique=False)
    op.create_table('user_learning_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_resource_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_chapters', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('daily_bite_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['learning_resource_id'], ['learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_resource_id', 'user_id', name='uq_lr_user')
    )
    op.create_index(op.f('ix_user_learning_progress_id'), 'user_learning_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_learning_progress_user_id'), 'user_learning_progress', ['user_id'], unique=False)
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_learning_progress_id', sa.Integer(), nullable=False),
    sa.Column('learning_resource_chapter_id', sa.Integer(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('quiz_attempted', sa.Boolean(), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learning_resource_chapter_id'], ['learning_resource_chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_learning_progress_id'], ['user_learning_progress.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_learning_progress_id', 'learning_resource_chapter_id', name='uq_ulp_lrc')
    )
    op.create_index(op.f('ix_user_chapter_progress_id'), 'user_chapter_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chapter_progress_id'), table_name='user_chapter_progress')
    op.drop_table('user_chapter_progress')
    op.drop_index(op.f('ix_user_learning_progress_user_id'), table_name='user_learning_progress')
    op.drop_index(op.f('ix_user_learning_progress_id'), table_name='user_learning_progress')
    op.drop_table('user_learning_progress')
    op.drop_index(op.f('ix_learning_resource_chapter_index'), table_name='learning_resource_chapter')
    op.drop_index(op.f('ix_learning_resource_chapter_id'), table_name='learning_resource_chapter')
    op.drop_table('learning_resource_chapter')
    op.drop_index(op.f('ix_learning_resource_title'), table_name='learning_resource')
    op.drop_index(op.f('ix_learning_resource_resource_type'), table_name='learning_resource')
    op.drop_index(op.f('ix_learning_resource_platform'), table_name='learning_resource')
    op.drop_index(op.f('ix_learning_resource_id'), table_name='learning_resource')
    op.drop_table('learning_resource')
    # ### end Alembic commands ###
