"""changed to index

Revision ID: 8d773873d291
Revises: 72eee569dabb
Create Date: 2026-01-21 19:15:31.822709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d773873d291'
down_revision: Union[str, Sequence[str], None] = '72eee569dabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_lr_title'), 'learning_resource_chapter', type_='unique')
    op.create_unique_constraint('uq_lr_index', 'learning_resource_chapter', ['learning_resource_id', 'index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lr_index', 'learning_resource_chapter', type_='unique')
    op.create_unique_constraint(op.f('uq_lr_title'), 'learning_resource_chapter', ['learning_resource_id', 'title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
