"""add job_id

Revision ID: bfc20f515c69
Revises: 8d773873d291
Create Date: 2026-02-10 19:31:21.484477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc20f515c69'
down_revision: Union[str, Sequence[str], None] = '8d773873d291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_learning_progress', sa.Column('job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_learning_progress', 'job_id')
    # ### end Alembic commands ###
